name: Generate Tokens on Input

on:
  push:
    branches:
      - main
    paths:
      - 'tokens/**/*.json'

jobs:
  generate_tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13
      - name: Install Node Dependencies
        run: npm ci
        env:
          YALESITES_BUILD_TOKEN: ${{ secrets.YALESITES_BUILD_TOKEN }}
      - name: Build Style Dictionary
        run: npm run build
      - name: Commit Generated Platform Deliverables
        uses: EndBug/add-and-commit@v7
        with:
          add: 'build -f'
          message: 'build: update design tokens'
      - name: Release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          YALESITES_BUILD_TOKEN: ${{secrets.YALESITES_BUILD_TOKEN}}
        run: npm run semantic-release
      - name: Remove Build Directory
        uses: EndBug/add-and-commit@v7
        with:
          remove: '--cached -r build'
          message: 'build: removed build directory from git'
