name: Generate Tokens on Input

on:
  push:
    paths:
      - 'tokens/**/*.json'

jobs:
  generate_tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13
      - name: Install Node Dependencies
        run: npm ci
        env:
          YALESITES_BUILD_TOKEN: ${{secrets.YALESITES_BUILD_TOKEN}}
      - name: Build Style Dictionary
        run: npm run build
      - name: Commit Generated Platform Deliverables
        id: "auto-commit-action"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: release
          add_options: '-f'
          commit_message: 'build: update design tokens'
